#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LineLeft,       sensorLineFollower)
#pragma config(Sensor, in2,    LineCenter,     sensorLineFollower)
#pragma config(Sensor, in3,    LineRight,      sensorLineFollower)
#pragma config(Sensor, in4,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  BumpSensor,     sensorDigitalIn)
#pragma config(Sensor, dgtl2,  InputButton,    sensorDigitalIn)
#pragma config(Sensor, dgtl3,  RightSonar,     sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  LeftSonar,      sensorSONAR_inch)
#pragma config(Sensor, dgtl7,  ServoSonar,     sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  LeftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  RightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           LeftDrive1,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           LeftDrive2,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           RightDrive1,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           RightDrive2,   tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           SonarServo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/************************************/
/* Senior Project                   */
/* V0.10 - Basic Setup              */
/*        April 10th                */
/* V0.11 - Demo                     */
/*        April 11th                */
/* V0.12 - Path Demos               */
/*        April 23rd                */

/************************************/

/* Constants */
const int 	OBSTACLE_COUNT = 10;
const float	TURN_CONV = 1.0; //Conversion rate for Degrees to encoder value for turning
const float	STAIGHT_CONV = 9.0; //Conversion rate for Inches to encoder values for regular driving

/* Include Files */
#include "Objects.c";
#include "Control.c";
#include "FieldGeneration.c";
#include "DrivePath.c";
#include "Path.c";

//SetPoints
Target startPoint;
Target endPoint;

//List of Undetermined obstacles
Obstacles obstacles;

task main()
{
	//Display Status
	displayStatus(0, "Calibrating Gyro");
	displayStatus(1, "Senior Project");

	//Allow the gyro to calibrate
	calibrateGyro(2000);

	//Display Field Status
	displayStatus(0, "Generating Field");

	//Assign a new field to the robot
	generateObstacles(0, obstacles);

	//Assign new targets to startPoint and endPoint
	//NOTE: Coordinantes start at bottom left
	newTarget(startPoint, 0, 0);
	newTarget(endPoint, 40, 30);

	//Display Setup Status
	displayStatus(0, "Setup Complete");

	//Tests if line intersects a region around an obstacle
	doesPathIntersectObstacle(10, 20, 50, 55, 30, 25, 5);




}
